[build]
command = "npm run build"
publish = "dist"
environment = { NODE_VERSION = "16" }

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[dev] # Command to start your dev server
targetPort = 3000 # The port for your application server, framework or site generator          # The port that the netlify dev will be accessible on
